### ISSUE TITLE
Régression constatée au lancement du service rstudio

### ISSUE THREAD

**Issue by RLesur** [InseeFrLab/onyxia-ui#111] opened 2020-04-23 20:12 UTC
Après avoir créé un nouveau [service rstudio](https://spyrales.sspcloud.fr/my-lab/catalogue/inseefrlab-datascience/rstudio/), le service n'affiche plus comme auparavant l'icône d'ouverture mais celle de redémarrage (alors que le service a bien été démarré).  
Voir le service de droite dans la capture ci-dessous : 

![Capture du 2020-04-23 22-10-23](https://user-images.githubusercontent.com/19177171/80144700-49136400-85af-11ea-8b01-434d41042693.png)

Lorsqu'on rafraichit la page, on obtient bien l'icône d'ouverture : 

![Capture du 2020-04-23 22-11-52](https://user-images.githubusercontent.com/19177171/80144819-7bbd5c80-85af-11ea-8d54-1414a5c8bdf8.png)

**Comment by olevitt** [comment] 2020-04-23 20:15
@Donatien26 : looks like a regression from today's merge, probably related to the way we determine the service status. Do you have time to investigate ?

**Comment by olevitt** [comment] 2020-04-24 17:26
For anyone wondering : this page is undergoing a massive revamp in branch `Feat/my-services` https://github.com/InseeFrLab/onyxia-ui/tree/Feat/my-services  

This issue (and many other bugs) should be fixed once the revamp is done.  
Sadly no estimate on how much time it will take. Help is obviously welcome :smiley:

**Comment by olevitt** [comment] 2020-05-04 11:18
This has been fixed in `v0.2` released few hours ago.  
If you experience this bug again, feel free to reopen this issue.

**Closed by olevitt** 2020-05-04 11:18 UTC
